grafana:
    adminUser: ENC[AES256_GCM,data:/w5uQB0=,iv:dkcgqQ4PoUl8KsaB4/cx/MKmZUB4zRIJYCTkXSsctC8=,tag:BT++ZvHjnYJcpoQ+ojRbTQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:4+NyzGOPGfU=,iv:DT7DaDhh61Bj8SAajynIYem/cRxIgMKJCHH0CR0sBLk=,tag:bX8r9DVTf9ZP3/skG5upGA==,type:str]
sops:
    age:
        - recipient: age1kgq9e4r3fe4yjns78nwndkfwj26eazuny9ww6hlf5l9ttcn9hu3qp4nlut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN2hMWXhIK2dxbTRJN1d3
            ajRsa3VYa1FMMFpzbmZtWnMxOVVqSVB0blRnCjdNalNJYnpoUDRVeUp6eHVNMXVJ
            WFpEMnpUSWhtRXdmaDh5OHF4cllXZUkKLS0tIGNnckQzM3FFV2xsYzJrU2FqaXZ0
            ZWpZMUpnbEthTEZPQ2o4QXNNemM4SnMKUZMGRvHvIoiDnpF9ts05xBhSizIm154p
            dfmGd3mlZcWlSGIjMBIkyR8nceHp1eKFNvR7JgxqRS55Mnx80bwfRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-21T13:41:58Z"
    mac: ENC[AES256_GCM,data:Zj2Oy9WPP5DRhvbo4PexuraueWQO+52M1bIXLJMM/kWpRUNVqLcuJ3P7Cz0i1C2h9mqiMS0vIXUKZ0YxFCuX1OzpbY7tImIxSKBzt65HVBPku2NxdAK7WC59+/I6FgvJCDDOqZdzB7uOgI7ENgfsG9Fgt6+yV9AIQMM5SZI2Cis=,iv:E46H43kGuC376yfplIXqM8l+0cH0gspRmx6G1Lq3HSI=,tag:kE6vgj1cRG1kjyUnUaDl4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
