helmDefaults:
  wait: true
  timeout: 600
  createNamespace: true
  atomic: true

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

environments:
  dev:
    values:
      - environments/dev.yaml

---
releases:
  - name: monitoring
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 77.12.0
    values:
      - values/prometheus/values.yaml
      - environments/{{ .Environment.Name }}.yaml
    # disableValidation: true # Please comment this line after the first install, its a work around helm-diff issue regarding CRDs
