apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Ymishkhas/kind-cluster-nginx.git
        revision: HEAD
        directories:
          - path: infra/istio/*
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: >-
          {{- if eq .path.basename "base" -}}20
          {{- else if eq .path.basename "istiod" -}}22
          {{- else if eq .path.basename "gateway" -}}24
          {{- else -}}26{{- end -}}
    spec:
      project: default
      source:
        repoURL: https://github.com/Ymishkhas/kind-cluster-nginx.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: istio-system
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istio-validator-istio-system
          jsonPointers:
            - /webhooks/0/failurePolicy
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
          jsonPointers:
            - /webhooks/0/failurePolicy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true 
