apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "22" }
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  source:
    repoURL: https://github.com/Ymishkhas/kind-cluster-nginx.git
    targetRevision: HEAD
    path: infra/istio/istiod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
