apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "10" }
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://github.com/Ymishkhas/kind-cluster-nginx.git
    targetRevision: HEAD
    path: infra/monitoring
    helm:
      valueFiles:
        - values.yaml
        - secrets://secrets.yaml
      ignoreMissingValueFiles: true 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
      - Validate=false # helpful on first install for CRDs
