releaseName: dev

# They’ll merge after values/prometheus/values.yaml
grafana:
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

prometheus:
  prometheusSpec:
    retention: "7d"     # shorter history for dev
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"