releaseName: dev

# They’ll merge after values/prometheus/values.yaml
prometheus:
  prometheusSpec:
    retention: "7d"     # shorter history for dev
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"