gateway:
  labels:
    istio: ingressgateway
  service:
    type: ClusterIP
    ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
gatewayName: main-gw
gatewayNamespace: istio-system
infraHosts:
  - argocd.localhost
  - grafana.localhost
  - prom.localhost
argocd:
  enabled: true
  host: argocd.localhost
grafana:
  enabled: true
  host: grafana.localhost
prometheus:
  enabled: true
  host: prom.localhost
