apiVersion: v2
name: nginx
version: 0.1.0
type: application
dependencies:
- repository: "oci://registry-1.docker.io/bitnamicharts"
  version: 18.1.8
  name: postgresql
  condition: preview.database.enabled
- repository: "oci://registry-1.docker.io/bitnamicharts"
  version: 24.0.0
  name: redis
  condition: preview.redis.enabled