apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  labels:
    app: nginx
    component: exporter
spec:
  selector:
    app: nginx
  ports:
    - name: http-metrics
      port: {{ .Values.ports.metrics }}
      targetPort: {{ .Values.ports.metrics }}