{{- if .Values.preview.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-connection
  labels:
    app: nginx
type: Opaque
stringData:
  # stringData means kubernetes will base64 encode it automatically
  DATABASE_URL: "postgresql://{{ .Values.preview-postgres.auth.username }}:{{ .Values.preview-postgres.auth.password }}@{{ .Release.Name }}-preview-postgres:5432/{{ .Values.preview-postgres.auth.database }}"
{{- end }}