apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  labels:
    app: nginx
    component: exporter
spec:
  selector:
    app: nginx
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113